version: '2'

services:
    couchbase-master:
        image: couchbase:latest
        ports:
            - 8091:8091
            - 8092:8092
            - 8093:8093

    gittalent-backend:
        image: gittalent-backend
        ports:
            - 8000:8080
        environment:
            - GITHUB_LOGIN=username
            - GITHUB_PASSWORD=password
        restart: always

    gittalent-frontend:
        image: gittalent-frontend
        ports:
            - 8001:80
        restart: always